import React from 'react';
import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { FileText, Download } from 'lucide-react';

const API_BASE = 'http://localhost:8000/api';

function PRD() {
  const { data, isLoading } = useQuery({
    queryKey: ['prd'],
    queryFn: async () => (await axios.get(`${API_BASE}/governance/prd/generate?rec_id=1`)).data
  });

  if (isLoading) return <div>Generating PRD...</div>;

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <header className="flex justify-between items-center">
        <div>
          <h2 className="text-3xl font-bold text-slate-900">Product Requirements Document</h2>
          <p className="text-slate-500">AI-generated spec for approved recommendation</p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg font-medium hover:bg-slate-800 transition-colors">
          <Download size={18} /> Export Markdown
        </button>
      </header>

      <div className="bg-white p-12 rounded-2xl border border-slate-200 shadow-sm prose prose-slate max-w-none">
        <div className="flex items-center gap-3 mb-8 pb-8 border-b border-slate-100">
          <FileText className="text-brand-500" size={32} />
          <div>
            <h1 className="text-2xl font-black text-slate-900">Feature: Payment Retry Logic</h1>
            <p className="text-slate-400 text-sm">Generated by ProductLens AI • v1.0</p>
          </div>
        </div>
        
        <div className="whitespace-pre-wrap text-slate-700 leading-relaxed">
          {data?.prd || "Loading PRD content..."}
        </div>
      </div>
    </div>
  );
}

export default PRD;
